import { createHash } from "node:crypto";
import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

import type { AgentProfileManifest, AgentProfileVersion } from "@agents-cloud/agent-profile";

export interface WrittenProfileBundle extends AgentProfileManifest {
  rootDir: string;
  bundleHash: string;
}

interface PendingFile {
  path: string;
  content: string;
}

export async function writeProfileBundle(profile: AgentProfileVersion, rootDir: string): Promise<WrittenProfileBundle> {
  const pendingFiles: PendingFile[] = [
    { path: "profile.json", content: `${JSON.stringify(profile, null, 2)}\n` },
    { path: "SOUL.md", content: renderSoul(profile) },
    { path: "config.fragment.yaml", content: renderConfigFragment(profile) },
    { path: "skills/README.md", content: renderSkillsReadme(profile) },
    { path: "policy/tool-policy.json", content: `${JSON.stringify(profile.toolPolicy, null, 2)}\n` },
    { path: "policy/mcp-policy.json", content: `${JSON.stringify(profile.mcpPolicy, null, 2)}\n` },
    { path: "evals/eval-pack.json", content: `${JSON.stringify(profile.evalPack, null, 2)}\n` },
    { path: "scorecards/latest.json", content: `${JSON.stringify(profile.scorecard ?? null, null, 2)}\n` },
    { path: "CHANGELOG.md", content: renderChangelog(profile) },
  ];

  const manifestWithoutSelf: AgentProfileManifest = {
    schemaVersion: "agent-profile/v1",
    generatedAt: new Date(0).toISOString(),
    profileHash: hash(JSON.stringify(profile)),
    files: pendingFiles.map((file) => ({ path: file.path, sha256: hash(file.content) })),
  };
  const bundleHash = hash(JSON.stringify(manifestWithoutSelf.files));
  const manifest: WrittenProfileBundle = {
    ...manifestWithoutSelf,
    rootDir,
    bundleHash,
    files: [...manifestWithoutSelf.files, { path: "manifest.json", sha256: hash(`${JSON.stringify({ ...manifestWithoutSelf, bundleHash }, null, 2)}\n`) }],
  };

  await mkdir(rootDir, { recursive: true });
  for (const file of pendingFiles) {
    await mkdir(join(rootDir, file.path, ".."), { recursive: true });
    await writeFile(join(rootDir, file.path), file.content, "utf8");
  }
  await writeFile(join(rootDir, "manifest.json"), `${JSON.stringify(manifest, null, 2)}\n`, "utf8");

  return manifest;
}

function renderSoul(profile: AgentProfileVersion): string {
  return `# ${profile.role}\n\n## Mission\n${profile.mission}\n\n## Project Context\n${profile.projectContextSummary}\n\n## Behavior\n${profile.behavior.instructions.map((instruction) => `- ${instruction}`).join("\n")}\n\n## Communication\n- Cadence: ${profile.behavior.communicationCadence}\n- Report style: ${profile.behavior.reportStyle}\n- Escalation: ${profile.behavior.escalationPolicy}\n\n## Allowed tools\n${profile.toolPolicy.allowedTools.map((tool) => `- ${tool.toolId}: ${tool.description}`).join("\n") || "- none"}\n\n## Approval-required tools\n${profile.toolPolicy.approvalRequiredTools.map((tool) => `- ${tool.toolId}: ${tool.description}`).join("\n") || "- none"}\n`;
}

function renderConfigFragment(profile: AgentProfileVersion): string {
  return `profile_id: ${profile.profileId}\nprofile_version: ${profile.version}\nrole: ${JSON.stringify(profile.role)}\ntoolsets:\n  - skills\n  - file\n  - terminal\napproval_required_tools:\n${profile.toolPolicy.approvalRequiredTools.map((tool) => `  - ${tool.toolId}`).join("\n") || "  []"}\n`;
}

function renderSkillsReadme(profile: AgentProfileVersion): string {
  return `# Skills for ${profile.role}\n\nThis bundle is generated by the Agent Workshop. Runtime materialization should copy only approved skills into this directory.\n\nCurrent draft behavior adaptations:\n\n${profile.behavior.feedbackAdaptations.map((adaptation) => `- ${adaptation}`).join("\n")}\n`;
}

function renderChangelog(profile: AgentProfileVersion): string {
  return `# Changelog\n\n${profile.changeLog
    .map((entry) => `## ${entry.version}\n\n${entry.summary}\n\nEvidence:\n${entry.evidence.map((item) => `- ${item}`).join("\n")}`)
    .join("\n\n")}\n`;
}

function hash(content: string): string {
  return `sha256:${createHash("sha256").update(content).digest("hex")}`;
}
