"use client";

import * as React from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { ReloadIcon, DownloadIcon } from "@radix-ui/react-icons";
import {
  getControlApiArtifactDownloadUrl,
  getControlApiHealth,
  listControlApiWorkItemArtifacts,
  listControlApiWorkItemSurfaces,
  listControlApiWorkItems,
  type WorkItemArtifactRecord,
  type WorkItemRecord,
  type WorkItemSurfaceRecord
} from "../../lib/control-api";
import { useAuth } from "../auth-context";
import { useWorkspace } from "../workspace-context";
import { cn } from "../../lib/utils";
import { Panel } from "./panel";
import { SectionHeader } from "./section-header";
import { StatusPill } from "./status-pill";
import { Button } from "./button";
import { ArtifactTile } from "./artifact-tile";
import { GenUiSurface } from "./genui-renderer";
import { BrowserToolbar, BrowserFramePlaceholder } from "./browser-frame";

const reportMarkdown = `# Weekly competitor pricing review

Three competitors moved pricing this week. Two raised their highest plan and one introduced a new entry tier. The full report links each change back to the source page and highlights anomalies.

| Artifact | Status | Owner |
| --- | --- | --- |
| Launch narrative | Ready | Writer agent |
| Pricing dataset | Ready | Research agent |
| Preview website | Awaiting approval | Builder agent |

\`\`\`text
quality gate -> tests -> preview -> approval -> publish
\`\`\`
`;

const demoArtifacts = [
  {
    kind: "report",
    title: "Competitor pricing report",
    body:
      "Markdown summary with cited sources, comparison tables, and anomaly call-outs. Generated by the research run and validated against the price-tracker schema.",
    action: "Open document",
    href: "#document"
  },
  {
    kind: "website",
    title: "Launch preview website",
    body:
      "Static preview at *.preview.solo-ceo.ai. Includes copy variants, screenshots, and a launch checklist.",
    action: "Open site",
    href: "#preview"
  },
  {
    kind: "diff",
    title: "Generated pull request",
    body:
      "Builder produced a draft PR against the marketing repo. Source-control writes are gated by approval and brokered credentials.",
    action: "Open diff",
    href: "/runs"
  },
  {
    kind: "log",
    title: "Run ledger export",
    body: "Ordered run.event payloads, tool calls, and validator decisions.",
    action: "Open log",
    href: "/runs"
  }
];

export function ArtifactsBoard() {
  const { isAuthed, openSignIn } = useAuth();
  const { workspaceId } = useWorkspace();
  const api = getControlApiHealth();
  const live = isAuthed && api.configured;

  const [items, setItems] = React.useState<WorkItemRecord[]>([]);
  const [selected, setSelected] = React.useState<string | null>(null);
  const [artifacts, setArtifacts] = React.useState<WorkItemArtifactRecord[]>([]);
  const [surfaces, setSurfaces] = React.useState<WorkItemSurfaceRecord[]>([]);
  const [loading, setLoading] = React.useState(false);
  const [error, setError] = React.useState<string | null>(null);
  const [tick, setTick] = React.useState(0);

  React.useEffect(() => {
    if (!live) return;
    let cancelled = false;
    setLoading(true);
    setError(null);
    (async () => {
      try {
        const r = await listControlApiWorkItems({ workspaceId, limit: 50 });
        if (cancelled) return;
        setItems(r.workItems);
        setSelected((cur) => cur ?? r.workItems[0]?.workItemId ?? null);
      } catch (err) {
        if (!cancelled) setError(err instanceof Error ? err.message : "Could not load work items.");
      } finally {
        if (!cancelled) setLoading(false);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [live, workspaceId, tick]);

  React.useEffect(() => {
    if (!live || !selected) return;
    let cancelled = false;
    (async () => {
      try {
        const [a, s] = await Promise.all([
          listControlApiWorkItemArtifacts({ workspaceId, workItemId: selected }).catch(() => ({
            artifacts: []
          })),
          listControlApiWorkItemSurfaces({ workspaceId, workItemId: selected }).catch(() => ({
            surfaces: []
          }))
        ]);
        if (cancelled) return;
        setArtifacts(a.artifacts);
        setSurfaces(s.surfaces);
      } catch (err) {
        if (!cancelled) setError(err instanceof Error ? err.message : "Could not load artifacts.");
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [live, workspaceId, selected]);

  return (
    <div className="flex flex-col gap-3 p-2 md:p-3.5">
      <SectionHeader
        title="Artifacts"
        subtitle="Reports, websites, diffs, and logs durably stored in S3 and surfaced back into every client."
      />

      <div className="flex flex-wrap gap-1.5">
        {!live ? (
          <StatusPill label="Demo mode" tone="warning" />
        ) : (
          <>
            <StatusPill label={`workspace: ${workspaceId}`} tone="info" />
            <StatusPill label={`${items.length} work items`} tone="info" />
            <StatusPill label={`${artifacts.length} artifacts`} tone="success" />
            <StatusPill label={`${surfaces.length} surfaces`} tone="success" />
          </>
        )}
        {loading ? <StatusPill label="Loading…" tone="info" /> : null}
      </div>

      {!live ? (
        <Panel padding={12} className="flex items-center justify-between gap-3">
          <div>
            <div className="text-sm font-extrabold text-app-text">Sign in to load real artifacts</div>
            <div className="mt-1 text-[12px] text-app-muted">
              The grid below shows the Flutter spec content.
            </div>
          </div>
          <Button variant="primary" size="md" onClick={openSignIn}>
            Sign in
          </Button>
        </Panel>
      ) : null}

      {error ? (
        <div className="rounded-[8px] border border-[#7F1D1D]/60 bg-[#7F1D1D]/10 p-2.5 text-[12px] text-[#ff8f8f]">
          {error}
        </div>
      ) : null}

      <div className="flex flex-col gap-3 xl:flex-row">
        <div className="xl:flex-[6] min-w-0 flex flex-col gap-3">
          {live ? (
            <Panel padding={14}>
              <SectionHeader
                title="Work items"
                trailing={
                  <Button variant="outline" size="sm" onClick={() => setTick((n) => n + 1)}>
                    <ReloadIcon /> Refresh
                  </Button>
                }
              />
              <div className="mt-3 flex flex-wrap gap-1.5">
                {items.map((item) => (
                  <button
                    key={item.workItemId}
                    type="button"
                    onClick={() => setSelected(item.workItemId)}
                    className={cn(
                      "rounded-[6px] border px-2.5 py-1.5 text-[11px] font-bold",
                      item.workItemId === selected
                        ? "bg-app-input border-app-text text-app-text"
                        : "bg-app-panel border-app-border text-app-muted hover:text-app-text"
                    )}
                  >
                    {item.title || item.objective}
                  </button>
                ))}
                {items.length === 0 ? (
                  <div className="text-[12px] text-app-muted">No work items yet.</div>
                ) : null}
              </div>
            </Panel>
          ) : null}

          <Panel padding={14}>
            <SectionHeader
              title="Artifact workspace"
              subtitle={
                live
                  ? "Artifacts produced by the selected work item's runs."
                  : "Every run writes durable artifacts; clients render but never own them."
              }
            />
            <div className="mt-3 grid grid-cols-1 gap-2.5 sm:grid-cols-2">
              {live ? (
                artifacts.length > 0 ? (
                  artifacts.map((a) => <RealArtifactTile key={a.artifactId} artifact={a} />)
                ) : (
                  <div className="text-[12px] text-app-muted col-span-2">
                    No artifacts for the selected work item yet.
                  </div>
                )
              ) : (
                demoArtifacts.map((a) => <ArtifactTile key={a.title} {...a} />)
              )}
            </div>
          </Panel>
        </div>

        <div className="xl:flex-[5] min-w-0 flex flex-col gap-3">
          {live && surfaces.length > 0 ? (
            <Panel id="document" padding={14}>
              <SectionHeader
                title="Generated surfaces"
                subtitle="Server-validated A2UI/GenUI surfaces, rendered via the allowlist."
              />
              <div className="mt-3 flex flex-col gap-3">
                {surfaces.slice(0, 3).map((s) => (
                  <GenUiSurface key={s.surfaceId} surface={s} />
                ))}
              </div>
            </Panel>
          ) : (
            <Panel id="document" padding={14}>
              <SectionHeader
                title="Markdown document viewer"
                subtitle="In-app rendering of report-style artifacts."
              />
              <div className="mt-3 rounded-[12px] border border-app-border bg-app-input p-3">
                <div className="ac-prose">
                  <ReactMarkdown remarkPlugins={[remarkGfm]}>{reportMarkdown}</ReactMarkdown>
                </div>
              </div>
            </Panel>
          )}

          <Panel id="preview" padding={14}>
            <SectionHeader
              title="Embedded browser shell"
              subtitle="Preview generated sites in-line. Hooks into preview hosting once published."
            />
            <div className="mt-3 flex flex-col gap-2.5">
              <BrowserToolbar url="https://solo-ceo.ai" />
              <BrowserFramePlaceholder />
            </div>
          </Panel>
        </div>
      </div>
    </div>
  );
}

function RealArtifactTile({ artifact }: { artifact: WorkItemArtifactRecord }) {
  const [downloading, setDownloading] = React.useState(false);
  const [downloadError, setDownloadError] = React.useState<string | null>(null);

  async function onDownload() {
    if (!artifact.runId) {
      setDownloadError("Artifact is not bound to a run.");
      return;
    }
    setDownloading(true);
    setDownloadError(null);
    try {
      const { url } = await getControlApiArtifactDownloadUrl({
        runId: artifact.runId,
        artifactId: artifact.artifactId
      });
      window.open(url, "_blank", "noopener,noreferrer");
    } catch (err) {
      setDownloadError(err instanceof Error ? err.message : "Download failed.");
    } finally {
      setDownloading(false);
    }
  }

  return (
    <div className="flex flex-col gap-2 rounded-[12px] border border-app-border bg-app-input p-3 h-full">
      <div className="flex flex-wrap gap-1.5">
        <StatusPill label={artifact.kind || "artifact"} />
        <StatusPill label={artifact.state || "ready"} tone="success" />
        {artifact.s3Uri ? <StatusPill label="S3" tone="warning" /> : null}
        {artifact.previewUrl ? <StatusPill label="Preview" tone="success" /> : null}
      </div>
      <div className="text-sm font-black text-app-text truncate">
        {artifact.name || artifact.artifactId}
      </div>
      <div className="flex-1 text-[12px] leading-[1.3] text-app-muted line-clamp-3">
        {artifact.contentType || ""}
        {artifact.sizeBytes ? ` · ${formatBytes(artifact.sizeBytes)}` : ""}
        {artifact.s3Uri ? `\n${artifact.s3Uri}` : ""}
        {artifact.previewUrl ? `\n${artifact.previewUrl}` : ""}
      </div>
      {artifact.previewUrl ? (
        <Button variant="primary" size="sm" onClick={() => window.open(artifact.previewUrl, "_blank", "noopener,noreferrer")}>
          Open preview
        </Button>
      ) : null}
      <Button variant="outline" size="sm" onClick={onDownload} disabled={downloading}>
        <DownloadIcon /> {downloading ? "Preparing…" : "Download"}
      </Button>
      {downloadError ? (
        <div className="text-[11px] text-[#ff8f8f]">{downloadError}</div>
      ) : null}
    </div>
  );
}

function formatBytes(n: number) {
  if (n < 1024) return `${n} B`;
  if (n < 1024 * 1024) return `${(n / 1024).toFixed(1)} KB`;
  return `${(n / 1024 / 1024).toFixed(1)} MB`;
}
